# Configure cache for rust crates
cache:
  key: rust-deps
  paths:
    - target/*/.fingerprint/
    - target/*/deps/
    - target/*/build/

# Install build deps
before_script:
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends build-essential

# Pipeline stage layout
stages:
  - test
  - build

# Testing stages run cargo unit tests
test-deb-11:
  stage: test
  image: rust:bullseye
  script: cargo test --verbose --release

test-deb-10:
  stage: test
  image: rust:buster
  script: cargo test --verbose --release

# Build stages compile and create artifacts
build-deb-11:
  stage: build
  image: rust:bullseye
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/jirapush
    name: twjp-debian11
  rules:
    - if: '$CI_COMMIT_REF_SLUG =~ /^v(\d.?){1,3}$/'
  needs:
    - test-deb-11

build-deb-10:
  stage: build
  image: rust:buster
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/jirapush
    name: twjp-debian10
  rules:
    - if: '$CI_COMMIT_REF_SLUG =~ /^v(\d.?){1,3}$/'
  needs:
    - test-deb-10
