# Configure cache for rust crates
cache:
  key: rust-deps
  paths:
    - target/*/.fingerprint/
    - target/*/deps/
    - target/*/build/

# Pipeline stage layout
stages:
  - test
  - build
  - upload
  - release

# Testing stages run cargo unit tests
test-deb-11:
  stage: test
  image: rust:bullseye
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential binutils
  script: cargo test --verbose --release

test-deb-10:
  stage: test
  image: rust:buster
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential binutils
  script: cargo test --verbose --release

# Build stages compile and create artifacts
build-deb-11:
  stage: build
  image: rust:bullseye
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential binutils
  script:
    - cargo build --release
    - strip target/release/jirapush
    - mv target/release/jirapush target/release/jirapush-deb11
  artifacts:
    paths:
      - target/release/jirapush-deb11
    name: twjp-debian11
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v(\d.?){1,3}$/'
  needs:
    - test-deb-11

build-deb-10:
  stage: build
  image: rust:buster
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential binutils
  script:
    - cargo build --release
    - strip target/release/jirapush
    - mv target/release/jirapush target/release/jirapush-deb10
  artifacts:
    paths:
      - target/release/jirapush-deb10
    name: twjp-debian10
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v(\d.?){1,3}$/'
  needs:
    - test-deb-10

# Upload artifacts and create releases on version tag pipelines
release-upload:
  stage: upload
  image: curlimages/curl:latest
  needs:
    - job: build-deb-10
      artifacts: true
    - job: build-deb-11
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v(\d.?){1,3}$/'
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file target/release/jirapush-deb11 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/jirapush/$CI_COMMIT_TAG/jirapush-deb11"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file target/release/jirapush-deb10 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/jirapush/$CI_COMMIT_TAG/jirapush-deb10"'

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - release-upload
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v(\d.?){1,3}$/'
  script:
    - echo 'Marking release for $CI_COMMIT_TAG'
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "Automatic release"
    assets:
      links:
        - name: "jirapush-deb11"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/jirapush/$CI_COMMIT_TAG/jirapush-deb11"
        - name: "jirapush-deb10"
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/jirapush/$CI_COMMIT_TAG/jirapush-deb10"
